SAA-1105: Completed SASAMS 12.1.11 and 12.1.12.
OmnisamAdmin/Lucid-SAMS pull request #22
Opened 2022-09-02 07:21 UTC by zeemos10

2022-09-19 09:10 UTC, OmnisamAdmin approved these changes
@mmalaza @MMalaza96 to provide final approval.

2022-09-20 07:17 UTC, mmalaza requested changes
Looks good for the most part, just small changes required

2022-09-20 07:17 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +            }
Format your classes CTR + ALT + L , apply everywhere where necessary

2022-09-20 07:17 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/TopicsResource.java
> +public class TopicsResource extends AbstractLucidSAMSResource implements ILucidSAMSResource {
This resource should be called 'SubjectMainTopics' because we have to keep the naming consistent with the SA-SAMS schemas

2022-09-20 07:17 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/TopicsResource.java
> +    }
The AbstractDatabaseConnectionManager cannot be instantiated because it is abstract, it just provides behaviors and attributes to the children 'NSP' & 'Edusol'. We only need to make use of the below constructor with EdusolStruc :

public TopicsResource(EdusolStrucDatabaseConnectionManager edusolStrucDatabaseConnectionManager) throws LucidSamsExecutionException {
        super(edusolStrucDatabaseConnectionManager);
    }

2022-09-20 07:17 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/TopicsResource.java
> +        String sql = "INSERT INTO " + TABLE_NAME + "( MainPosition, Description, AfrDescription)"
Please try avoiding trailing whitespace, replace "(  MainPosition, Description" with "(MainPosition, Description" . Apply wherever else applicable

2022-09-20 07:17 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/sams/lucid/schema/Topics.java
> + *           &lt;/simpleType&gt;
We don't need this class because Keenan generates the schemas for us, so wherever you reference this you can replace it with "SubjectMainTopics". Please delete this class and replace its usages.

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +public class TopicsController {
Our naming needs to follow the SA-SAMS schemas, so this needs to be called "SubjectMainTopicsController" .

Remember to update references to the new controller name.

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +@RequestMapping("Topics")
Naming needs to follow SA-SAMS schemas so this will change to "SubjectMainTopics" but according to Richards Bayer's principles for how we name and design services the request mapping name will change to "subject-main-topics".  

Please read up on this standard

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +     */
If you going to write java documentation, please ensure its fully thrust out otherwise rather leave it out.

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/TopicsMapper.java
> +public class TopicsMapper {
Update TopicsMapper to "SubjectMainTopicsMapper"

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/TopicsMapper.java
> +            topics.setMainPosition(String.valueOf(topicsRequests.getMainPosition()));
Please try avoiding having too many dot operators on one line, our limit is 3. So, although this is not violating that limiting your use of dot operators on one line makes your code easier to debug. Rather do the following since you have already initialized the variable:  

topics.setMainPosition(String.valueOf(mainposition);

Apply this anywhere else in your code where applicable

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/TopicsMapper.java
> +        }
In a lot of your set methods, you are fetching a value from the request when you have it already just before you do a null check. If the variable is not null, you can safely place it in your setter

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/SubjectsService.java
> +
This save method returns an identifier value that we slap on the Subjects object and return it to our end user. We need to map this value on the object manually. Please do the following :  

Long generatedKey =  subjectsResource.save(subjects, subjectsResource);
subjects.setID((Math.toIntExact(generatedKey));

Apply wherever else applicable

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +    private final TopicsService TopicsService;
This must not be final

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/TopicsService.java
> +public class TopicsService {
This must be called "SubjectMainTopicsService"

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/TopicsService.java
> +        TopicsResource.save(Topics, TopicsResource);
This save method returns an identifier value that we slap on the Subjects object and return it to our end user. We need to map this value on the object manually. Please do the following :

Long generatedKey =  subjectMainTopicsResource.save(subjects, subjectMainTopicsResource);
subjectMainTopicsResource.setID((Math.toIntExact(generatedKey)); 
 //Please note not all resources have setID, some may have a different identifier so you may have to investigate

Apply wherever else applicable

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/TopicsService.java
> +    private final TopicsMapper TopicsMapper;
Variable naming convention violation: the first word is always lowercase and each word after that the first letter is uppercase

Please change "TopicsMapper" to "topicsMapper" and "TopicsResource" to "topicsResource"

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +public class TopicsRequests implements Serializable {
this needs to be changed to SubjectMainTopicsRequest

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +
remove unnecessary comments

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +    private Short verndescription;
Not sure if requests work with Short maybe it does but you may have to change this to Integer and then convert to Short in the corresponding Mapper class, remember to do a null check before you attempt conversion

2022-09-20 07:17 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsResponse.java
> +public class TopicsResponse extends ApiResponse implements Serializable {
Please change class name to SubjectMainTopicsResponse

2022-10-24 10:34 UTC, OmnisamAdmin commented
Fixed merge comments and tacking changes into the main branch.

2022-10-24 10:34 UTC, merged