Saa 1113
OmnisamAdmin/Lucid-SAMS pull request #24
Opened 2022-09-08 10:21 UTC by zeemos10

SAA-1113: SASAMS Module 12.1.14 and 12.1.16

2022-09-19 09:19 UTC, OmnisamAdmin approved these changes

2022-09-20 08:03 UTC, mmalaza requested changes
Looks good , small changes

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/EducatorsGroupResource.java
> +/**
Replace with your author name, take your kudos lol!! apply this on anything you've done.

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/EducatorsGroupResource.java
> +        String sql = "INSERT INTO " + TABLE_NAME + "( EducatorGroupID, Grade, EducatorId, GroupName, SubjectId )"
please remove trailing white space here '( EducatorGroupID' and here 'SubjectId )'

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/EducatorsGroupResource.java
> +
please remove unnecessary space

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectSetResource.java
> + */
Replace with your author name, take your kudos lol!! apply this on anything you've done.

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectSetResource.java
> +    }
The AbstractDatabaseConnectionManager cannot be instantiated because it is abstract, it just provides behaviors and attributes to the children 'NSP' & 'Edusol'. We only need to make use of the below constructor with EdusolStruc :

public TopicsResource(EdusolStrucDatabaseConnectionManager edusolStrucDatabaseConnectionManager) throws LucidSamsExecutionException {
super(edusolStrucDatabaseConnectionManager);
}

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectSetResource.java
> +        String sql = "INSERT INTO " + TABLE_NAME + "( Description, SubjectID, SubjectSetGrade )"
As mentioned in earlier comments, remove trailing whitespace

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectSetResource.java
> +
remove unnecessary space

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +                        + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
there's no space between ')' & 'VALUES', this may or may not mess up your query

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +                preparedStatement.setNull(10, Types.INTEGER);
formatting CTR + ALT + L

2022-09-20 08:03 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/TopicsResource.java
> + */
replace with your author name

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/EducatorsGroupController.java
> +@RequestMapping("Educatorgroups")
According to Richard Bayer's principle this should be called "educator-groups"

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/EducatorsGroupController.java
> +    private final EducatorsGroupService EducatorsGroupService;
variable name must be educatorsGroupService

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/EducatorsGroupController.java
> +    /**
remove

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/SubjectSetController.java
> +@RequestMapping("SubjectSets")
According to Richard Bayer's Principle this should be "subject-sets"

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/SubjectSetController.java
> +    /**
unless adding comprehensive java documentation rather remove

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +@RequestMapping("Topics")
rename to subject-main-topics

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +    @PostMapping(
unless adding comprehensive java documentation rather remove

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/EducatorsGroupMapper.java
> +
remove space

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/SubjectSetMapper.java
> +        return subjectsets;
remove space

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/SubjectSetMapper.java
> +    public SubjectSets SubjectSetRequestToSubjectSets(SubjectSetRequest subjectsetRequest) {
make first word lowercase

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/SubjectSetMapper.java
> +
Do we need this?

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/EducatorsGroupService.java
> +        EducatorsGroupResource.save(educatorgroups, EducatorsGroupResource);
This save method returns an identifier value that we slap on the Subjects object and return it to our end user. We need to map this value on the object manually. Please do the following :

Long generatedKey = educatorsGroupResource.save(subjects, educatorsGroupResource);
educatorsGroup.setID((Math.toIntExact(generatedKey));

Apply wherever else applicable

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/SubjectSetService.java
> +        SubjectSetResource.save(subjectsets, SubjectSetResource);
This save method returns an identifier value that we slap on the Subjects object and return it to our end user. We need to map this value on the object manually. Please do the following :

Long generatedKey = subjectsResource.save(subjects, subjectsResource);
subjects.setID((Math.toIntExact(generatedKey));

Apply wherever else applicable

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/TopicsService.java
> +        TopicsResource.save(Topics, TopicsResource);
similar issue to the other save methods, use the returned generatedKey

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/SubjectSetRequest.java
> +    private Short description;
May have to consider making this Integer and converting to short in your mapper. remember null check before conversion

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +    private Short verndescription;
May have to consider making this Integer and converting to short in your mapper. remember null check before conversion

2022-09-20 08:03 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +    /**
remove

2022-10-24 13:24 UTC, merged