Saa 1132
OmnisamAdmin/Lucid-SAMS pull request #26
Opened 2022-09-17 17:57 UTC by zeemos10

Module 12.3.11

2022-09-19 09:19 UTC, OmnisamAdmin approved these changes

2022-09-20 08:23 UTC, mmalaza requested changes
Small changes

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/EducatorsGroupResource.java
> +    }
only use
-->

 public EducatorsGroupResource(EdusolStrucDatabaseConnectionManager edusolStrucDatabaseConnectionManager) throws LucidSamsExecutionException {
        super(edusolStrucDatabaseConnectionManager);
    }

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/EducatorsGroupResource.java
> +        String sql = "INSERT INTO " + TABLE_NAME + "( EducatorGroupID, Grade, EducatorId, GroupName, SubjectId )"
trailing whitespace by brackets

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/EducatorsGroupResource.java
> +
trailing whitespace

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectCriteriaResource.java
> +    }
only use     
-->

public SubjectCriteriaResource(EdusolStrucDatabaseConnectionManager edusolStrucDatabaseConnectionManager) throws LucidSamsExecutionException {
        super(edusolStrucDatabaseConnectionManager);
    }

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectCriteriaResource.java
> +            preparedStatement.setInt(1,subjectcriteria.getSubjectID());
Format and remove trailing whitespace

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectCriteriaResource.java
> +
remove

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectCriteriaResource.java
> +
remove

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectSetResource.java
> +    }
only use  

   public SubjectSetResource(EdusolStrucDatabaseConnectionManager edusolStrucDatabaseConnectionManager) throws LucidSamsExecutionException {
        super(edusolStrucDatabaseConnectionManager);
    }

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectSetResource.java
> +
remove

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +                 Short SubjectStatus = subjects.getSubjectStatus();
format

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +
aren't we using  officialSubjectID  ?

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +              Integer CTAWeight = subjects.getCTAWeight();
naming convention violation, please read up on java naming conventions and apply changes everywhere where necessary.

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/SubjectsResource.java
> +            }
Not using subjectGrade?

2022-09-20 08:23 UTC, mmalaza commented on resource/src/main/java/za/co/sfy/lucid/sams/resource/TopicsResource.java
> +    }
only use    


 public TopicsResource(EdusolStrucDatabaseConnectionManager edusolStrucDatabaseConnectionManager) throws LucidSamsExecutionException {
        super(edusolStrucDatabaseConnectionManager);
    }****

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +@RequestMapping("Topics")
rename to topics

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +    private final TopicsService TopicsService;
naming convention violation

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/controller/TopicsController.java
> +    /**
unless adding comprehensive java docs rather remove

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/SubjectCriteriaMapper.java
> +        }
you not making use of the variables you initialized, please fix this throughout your changes.

e.g.  subjectcriteria.setSubjectLevel(subjectcriteriaRequest.getDataYear()); should be  subjectcriteria.setSubjectLevel(datayear);

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/SubjectSetMapper.java
> +}
Is this necessary?

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/mapper/TopicsMapper.java
> +        if (null != reclocked) {
Same issue as earlier, not making use of initialized variables

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/EducatorsGroupService.java
> +        EducatorsGroupResource.save(educatorgroups, EducatorsGroupResource);
check earlier cooments regarding save methods and using generatedKeys

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/SubjectCriteriaService.java
> +        SubjectCriteriaResource.save(subjectcriteria, SubjectCriteriaResource);
check earlier comments regarding saves

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/service/SubjectSetService.java
> +        SubjectSetResource.save(subjectsets, SubjectSetResource);
check earlier comments regarding saves

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/SubjectCriteriaRequest.java
> +    private Short descriptionvern;
Consider replacing Short with Integer, if request work with short then you dont have to

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/SubjectSetRequest.java
> +    private Short description;
may have to replace datatype with Integer

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +    private Short verndescription;
May have to consider using Integer instead of Short

2022-09-20 08:23 UTC, mmalaza commented on services/src/main/java/za/co/sfy/lucid/sams/rest/vo/data/writer/TopicsRequests.java
> +    /**
remove

2022-10-31 19:45 UTC, merged